# ------
# MODELS
# ------

diffusion: 

  params:
    n_obs_steps: 1
    horizon: 16    
    n_action_steps: 8

  sampling:
    fps_sampling_hist: 10
    fps_sampling_chunk: 10


act:

  params:
    n_obs_steps: 1
    chunk_size: 50   
    n_action_steps: 25
    # use_vae: "False"
    kl_weight: 0.0

  sampling:
    fps_sampling_hist: 10
    fps_sampling_chunk: 10


flow: 

  params:
    n_obs_steps: 1
    horizon: 16    
    n_action_steps: 8
    #vision_backbone: "vit_b_16"
    #pretrained_backbone_weights: "ViT_B_16_Weights.IMAGENET1K_V1"

  sampling:
    fps_sampling_hist: 10
    fps_sampling_chunk: 10


my_policy:

  params:
    N_history: 3
    N_chunk: 16
    n_action_steps: 8

  sampling:
    fps_sampling_hist: 30
    fps_sampling_chunk: 30