# ---------
# INFERENCE
# ---------

inference:

  pretrained_policy_abs_path: "/workspace/outputs/checkpoints/today_outliers_DP_2025-12-02_17-10-22/best_model.pt"
  configs_dataset_rel_path: "../workspace/outputs/checkpoints/today_outliers_DP_2025-12-02_17-10-22/dataset.yaml"  # saved with model weights
  configs_models_rel_path: "../workspace/outputs/checkpoints/today_outliers_DP_2025-12-02_17-10-22/models.yaml"    # saved with model weights
  policy_rate: 30 # for now, it shall be the same as: fps_sampling_chunk
  fps_dataset: 29.995 # it shall be the fps got from the dataset (info.json) used for training
  policy_name: "diffusion" # [diffusion, act]
