# --------
# TRAINING
# --------

training:

  training_steps: 4000     # number of training steps
  log_freq: 200            # logs train loss, gradNorm, lr
  eval_freq: 2000          # logs eval loss
  save_ckpt_freq: 2000     # save checkpoints
  learning_rate: 0.00001
  lr_warmup_steps: 500
  weight_decay:  0.0001 


# -------------
# NORMALIZATION
# -------------

normalization_mapping:

  VISUAL: "MEAN_STD"
  STATE: "MIN_MAX"
  ACTION: "MIN_MAX"